README.mdにER図へのリンクを記載
KeitaroOtsuka/CheifGasEngineer pull request #4
Opened 2022-05-12 16:03 UTC by KeitaroOtsuka

ER図を作成しましたので、お手隙の際にご確認お願いいたします。

https://drive.google.com/file/d/1TpEvo2IkF84UK3gUGsmuRVoq2zRQqm4J/view?usp=sharing
READMEにも書かせていただいておりますが、こちらがリンクになります。

2022-05-12 22:30 UTC, takyyk commented
@KeitaroOtsuka 
すいません、こちらアクセス権が要求されるので見れる状態にしてください！

2022-05-13 03:28 UTC, KeitaroOtsuka commented
すみません。変更いたしました。

2022-05-13 03:29 UTC, KeitaroOtsuka commented
> @KeitaroOtsuka すいません、こちらアクセス権が要求されるので見れる状態にしてください！

2022-05-13 03:31 UTC, KeitaroOtsuka commented
@takyyk 
すみません。変更いたしました。

2022-05-13 07:58 UTC, yuji91 requested changes
以下気になった点です！
- `result`は試験とユーザーの中間テーブルなので、`User`に`result_id`を持たせるのではなく`Result`に`user_id`を持たせるのが良さそうです。
- `all_answers`に`integer`を持たせても回答は表現出来なそうです。（選択した答えの配列を持てるようにStringにすべき？）
- `year`はテーブルに分ける必要はなさそうです。
- `Exams`テーブルに`choice_id`を持たせるのではなく、`Choices`テーブルに`exam_id`を持たせるべきかと思いました。また`choices`というカラム名より`body`の方が被らなくて良さそうです。
- 画面遷移図を確認する限りでは、論述形式の問題の表示は想定せずに4択に絞って対応しているかと思いました。その場合、4択で正解が1つだけなのであれば、ExamsのanswerはIDを入れる形でIntegerにするか、Choicesのレコードに正解か不正解かを判定できるBooleanを入れてもいいと思いました。

2022-05-13 22:13 UTC, KeitaroOtsuka commented
@yuji91 
見ていただきありがとうございます。いただいたアドバイスをもとに修正してみました。
https://drive.google.com/file/d/1TpEvo2IkF84UK3gUGsmuRVoq2zRQqm4J/view?usp=sharing

１点質問をさせていただきたいです。
ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
all_answersにintegerを持たせても回答は表現出来なそうです。（選択した答えの配列を持てるようにStringにすべき？）
ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
このポイントに関してですが、僕としては解いた問題数をall_answerに格納してそのうち正解していた問題数をcorrect_answerにも入れることで解き終わった後に正答率などを表示したいと考えているのですがこのテーブル設計だとそれは難しいのでしょうか。

2022-05-14 02:29 UTC, murata0705 commented
> このポイントに関してですが、僕としては解いた問題数をall_answerに格納してそのうち正解していた問題数をcorrect_answerにも入れることで解き終わった後に正答率などを表示したいと考えているのですがこのテーブル設計だとそれは難しいのでしょうか。

こちらの仕様なら、今のままで大丈夫そうですね。
下記テーブルにどんな値が入るかサンプルを貰ってもいいですか？甲乙とか法令とかどんなデータが入るのか確認したく！

- category
- type
- exam

2022-05-14 02:31 UTC, murata0705 commented
また、試験のカテゴリの階層構造もしりたいです。3階層ですかね？

- 甲乙
	- 法令、ガス基礎、ガス技術
		- 製造、供給、消費

2022-05-14 08:49 UTC, KeitaroOtsuka commented
@murata0705 
q_kou_r3.pdf , a_kou_r3.pdf
こちらが令和3年甲種の問題と解答になります。

categoryで法令、ガス基礎、ガス技術(製造、供給、消費)を分け
typeで甲・乙に分けようと考えております。

2022-05-14 09:11 UTC, KeitaroOtsuka commented
@murata0705 
製造、供給、消費に関してはガス技術の分野に相当するのですが試験で足切りが存在するのは、
法令、ガス基礎、ガス技術
に関してだけですので２階層で十分なのではないかと思っています。

2022-05-15 01:58 UTC, murata0705 commented
> categoryで法令、ガス基礎、ガス技術(製造、供給、消費)を分け
typeで甲・乙に分けようと考えております。

甲乙は階層構造になっていないのであれば、exams テーブルに xxx_type のような形で属性でもたせるほうが一般的かなと思いました。category については了解です。

exams と choices テーブルのカーディナリティが、choices が exams を持つ形になっているので、意図していることと異なるかなと思いました。

また、exams と choices のカラムについてどんなデータが入るのかよくわからなかったので、ここに書いていただけますか？

- exams
  - id: 1
  - year: 2022
  - ...

のような形で、実際に db に入るデータを入れていただきたいです。

2022-05-16 06:51 UTC, yuji91 commented
横からすみません。面談で話したメモとなります。
Choisesテーブルについて、選択肢の本文（Choises.body）と選択肢を選んだ結果の判定（Choises.judge）が同じテーブルにありますが、前者はマスタデータ、後者はトランザクションデータの役割だと思うのでテーブルを分ける（judgeの内容をResultで記録するなど）を行った方が良いかと思います。

またExamsテーブルが「どの試験の内容か」と「どのような問題か」という役割が混ざってしまっているので、ExamsとQuestionsの２テーブルに分割するのが自然か印象を受けました。（もし何か不都合あればすみません。）

2022-05-16 23:19 UTC, KeitaroOtsuka commented
@murata0705 @yuji91 
おつかれさまです。コメントありがとうございます。
返信が遅くなりましたが、ご指摘・面談をもとに修正をしました。

examsテーブルに関してですが、questionsテーブルとわけることで
- exams
  - category_id:1
  - year_id:1
  - exam_type:1
  - title:令和3年甲種ガス主任試験問題

- questions
  - choices_id:2
  - exam_id:1
  - sentence:都市ガスの原料に関する~
  - answer:1
  - commentary:解説解説解説

resultsテーブルでは、解いた問題に対する正誤判定をjudgeで行い、最終的に解いた問題(resultテーブルのレコード数)と正解数(judgeがtrueのレコード数)で正答率を表したいと考えています。

2022-05-17 03:07 UTC, kerochelo commented
@KeitaroOtsuka 
確認しましたー！
1点確認です！

choisesテーブルはquestionsテーブルにある問題の選択肢情報っすよね？
そのため下記の指摘部分があった通り、questionsテーブルに`choise_id`を持たせる部分は変えた方がいいですね！

> 伊藤さん：Examsテーブルにchoice_idを持たせるのではなく、Choicesテーブルにexam_idを持たせるべきかと思いました。
> 村田さん：exams と choices テーブルのカーディナリティが、choices が exams を持つ形になっているので、意図していることと異なるかなと思いました。

現状をまとめると、choisesテーブルのカラムにどの問題の選択肢なのかを表すquestion_idを保存するようにするのがいいかと思います。

2022-05-17 04:56 UTC, yuji91 commented
菅野講師の指摘通り、`questions`テーブルと`choices`テーブルの関連性とどんなデータのレコードができるのかを考えると、1つの`questions`に複数（5つ）の`choices`テーブルのレコードが紐づく形になると思うので、choicesテーブルが親の`question_id`を持つ形になるかと思います！

引き続き、アソシエーションの関係性までイメージしながらテーブルの定義を考慮していきましょう！

2022-05-17 14:23 UTC, KeitaroOtsuka commented
@kerochelo 
コメントありがとうございます。
修正しました！

2022-05-19 22:34 UTC, KeitaroOtsuka commented
@kerochelo 
コメントありがとうございます。
何度もお手を煩わせてしまいすみません。
ご指摘いただいたポイントを修正しました。

意図したいこととしては、
Resultテーブル
・ResultChoicesのjudgeをカウントすることで試験全体の結果を表示する。

ResultChoicesテーブル
・judgeで判定した個々の問題を格納することで、間違えた問題を後から見直せるようにする。

です。
ご確認よろしくお願いいたします。

2022-05-20 03:19 UTC, kerochelo commented
@KeitaroOtsuka 
確認しましたー
LGTMです、実装に入っていきましょう！

これから機能修正や機能拡張する際にER図が変更、追加することがあると思いますが、その際には講師のレビューなどは通さなくてok
不安な場合は面談など入れていただき相談していただければですー！
![LGTM](https://image.lgtmoon.dev/166851)

2022-05-22 15:14 UTC, merged